"""
Guardrails for SQL generated by the LLM, executed *before* anything
touches the database. Defense in depth: this static check is layer one,
the read-only DuckDB connection (see db.py) is layer two, and a
statement timeout is layer three (see nl_query.py).
"""
from __future__ import annotations
import re
from dataclasses import dataclass

FORBIDDEN_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "REPLACE",
    "ATTACH", "DETACH", "COPY", "EXPORT", "IMPORT", "PRAGMA", "CALL",
    "INSTALL", "LOAD", "SET", "VACUUM", "GRANT", "REVOKE", "TRUNCATE",
    "MERGE", "CHECKPOINT",
]
ALLOWED_START = ("SELECT", "WITH")


@dataclass
class GuardResult:
    ok: bool
    reason: str | None = None
    cleaned_sql: str | None = None


def _strip_sql_comments(sql: str) -> str:
    sql = re.sub(r"--.*?$", "", sql, flags=re.MULTILINE)
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.DOTALL)
    return sql


def validate_sql(sql: str, allowed_table: str) -> GuardResult:
    if not sql or not sql.strip():
        return GuardResult(ok=False, reason="Empty SQL.")

    cleaned = _strip_sql_comments(sql).strip()
    cleaned = cleaned.rstrip(";").strip()

    if not cleaned:
        return GuardResult(ok=False, reason="SQL was empty after stripping comments.")

    # Only a single statement: no semicolon-separated chaining.
    if ";" in cleaned:
        return GuardResult(ok=False, reason="Multiple statements are not allowed.")

    first_word = re.split(r"\s+", cleaned.strip(), maxsplit=1)[0].upper()
    if first_word not in ALLOWED_START:
        return GuardResult(
            ok=False,
            reason=f"Only SELECT/WITH statements are allowed, got '{first_word}'.",
        )

    upper = cleaned.upper()
    for kw in FORBIDDEN_KEYWORDS:
        if re.search(rf"\b{kw}\b", upper):
            return GuardResult(ok=False, reason=f"Forbidden keyword detected: {kw}.")

    # CTE aliases (WITH x AS (...), y AS (...)) are legitimate "table" names
    # in the outer query and must not be flagged as unknown references.
    cte_aliases = {
        (m.group(1) or m.group(2)).strip('"').lower()
        for m in re.finditer(
            r"\bWITH\s+([a-zA-Z0-9_\"]+)\s+AS\s*\(|,\s*([a-zA-Z0-9_\"]+)\s+AS\s*\(",
            cleaned,
            re.IGNORECASE,
        )
    }

    # The generated SQL should only reference the one table it was given
    # (plus any CTEs it defined itself). This is a soft check (regex, not
    # a real parser) -- good enough to catch an LLM hallucinating a second
    # table name, not a security boundary on its own (the read-only
    # connection is the real boundary).
    referenced_tables = set(
        (m.group(1) or m.group(2)).strip('"')
        for m in re.finditer(r"\bFROM\s+([a-zA-Z0-9_\".]+)|\bJOIN\s+([a-zA-Z0-9_\".]+)", cleaned, re.IGNORECASE)
    )
    # normalize (drop schema qualifiers, quotes)
    normalized = {t.split(".")[-1].strip('"').lower() for t in referenced_tables if t}
    unknown = normalized - {allowed_table.lower()} - cte_aliases
    if unknown:
        return GuardResult(
            ok=False,
            reason=f"Query references unknown table(s): {sorted(unknown)}. "
                   f"Only '{allowed_table}' exists.",
        )

    return GuardResult(ok=True, cleaned_sql=cleaned)
